import { inject, observer } from "mobx-react";
import { useEffect, useState } from "react";
import { useHistory } from "react-router";
import "./serverForm.css";
import {
  Descriptions,
  Input,
  Upload,
  Button,
  message,
  Modal,
  Result,
  Spin,
  Timeline,
  Collapse,
  Radio,
  List,
  Select,
  Card,
  Steps,
  Popover,
} from "antd";

import {
  UploadOutlined,
  LoadingOutlined,
  InboxOutlined,
} from "@ant-design/icons";
import { submitForm } from "../../../stores/request";
import { REQUEST } from "../../../constants/status";
const { Panel } = Collapse;
const { Dragger } = Upload;
const { TextArea } = Input;
const antIcon = <LoadingOutlined style={{ fontSize: 16 }} spin />;
const { Option } = Select;
const { Step } = Steps;

function ServerForm(store) {
  const [aValue, setAValue] = useState(2);
  const [bValue, setBValue] = useState(2);
  const [testAddValue, setTestAddValue] = useState(0);

  useEffect(() => {
    console.log(store);
  }, []);
  useEffect(() => {
    if (store.store.servers.status === REQUEST) {
      setUploading(true);
    } else {
      setUploading(false);
    }
  }, [store.store.servers.status]);

  const [current, setCurrent] = useState(0);
  const [DAN_text, setDAN_text] = useState("");

  const [fileList, setFileList] = useState([]);
  const [testFileList, setTestFileList] = useState([]);

  const [uploading, setUploading] = useState(false);
  const [eMail, setEMail] = useState("");
  const [resultData, setResultData] = useState({
    jobId: null,
    requestTime: "2021-09-23 14:36:13",
    status: "waiting",
  });
  const [isModalVisible, setIsModalVisible] = useState(false);
  const history = useHistory();
  const onChange = (current) => {
    console.log("onChange:", current);
    setCurrent(current);
  };

  const showModal = async (data) => {
    await setResultData({
      jobId: data.jobId,
      requestTime: data.requestTime,
      status: data.status,
    });
    await setIsModalVisible(true);
  };

  const handleOk = () => {
    setIsModalVisible(false);
    history.push("/");
  };

  const props = {
    onRemove: (file) => {
      const index = fileList.indexOf(file);
      const newFileList = fileList.slice();
      newFileList.splice(index, 1);
      setFileList(newFileList);
    },
    beforeUpload: (file) => {
      if (file.name.substr(-5, 5) === "fasta") {
        console.log(file);
        setFileList([file]);
        const reader = new FileReader();
        reader.onload = function fileReadCompleted() {
          // 当读取完成时，内容只在`reader.result`中
          console.log(reader.result);
        };
        reader.readAsText(file);
      } else {
        message.info("please select file with tpye of fasta");
      }
      return false;
    },

    fileList,
  };

  const testProps = {
    onRemove: (file) => {
      const index = testFileList.indexOf(file);
      const newFileList = testFileList.slice();
      newFileList.splice(index, 1);
      setTestFileList(newFileList);
    },
    beforeUpload: (file) => {
      if (file.name.substr(-5, 5) === "fasta") {
        console.log(file);
        setTestFileList([file]);
        const reader = new FileReader();
        reader.onload = function fileReadCompleted() {
          // 当读取完成时，内容只在`reader.result`中
          console.log(reader.result);
        };
        reader.readAsText(file);
      } else {
        message.info("please select file with tpye of fasta");
      }
      return false;
    },

    testFileList,
  };

  const getFile = () => {
    var formData = new FormData();
    fileList.forEach((file) => {
      formData.append("file", file);
    });
    return formData;
  };
  const submit = async () => {
    let formData = getFile();
    //dataStr, dataFile, param, mail
    if (fileList[0]) {
      formData.append("dataFile", fileList[0], fileList[0].name);
    }
    formData.append("dataStr", DAN_text);
    formData.append("param", "{}");

    formData.append("mail", eMail);

    console.log(formData);
    if ((DAN_text != "" || fileList[0]) && eMail || (selectMulMethodData_1+selectMulMethodData_2+selectMulMethodData_3)>0) {
      store.store.servers.request();
      let result = await submitForm(formData);
      console.log(result);
      if (result.resultType) {
        store.store.servers.request_success();
        showModal(result.data);
      } else {
        store.store.servers.request_fail();
        message.error("failed");
      }
    } else {
      if(DAN_text == ""&&fileList.length==0){
        setStepStatus_step_1("red")
      }
      if(eMail==""){
        setStepStatus_step_4("red")
      }
      if((selectMulMethodData_1+selectMulMethodData_2+selectMulMethodData_3)==0){
        setStepStatus_step_3("red")
      }
      message.info("please input all data");
    }
  };
  const resetData = () => {
    setFileList([]);
    setEMail("");
    setDAN_text("");
  };
  const qwe = {
    model: ["CNN", "GCN", "wdwe"],
    balance: true,
    cdHit: false,
  };
  var xmlhttp;

  function loadData(url, cfunc) {
    xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = cfunc;
    /*修改服务端代码，进行全路由配置，允许跨域请求*/
    // xmlhttp.statusText="OPENED"
    // xmlhttp.setRequestHeader('Access-Control-Allow-Origin',  '*');

    //xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xmlhttp.open("GET", url, true);
    xmlhttp.send();
  }
  function readFile(url) {
    loadData(url, function () {
      if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
        setDAN_text(xmlhttp.responseText.toString());
        return xmlhttp.responseText;
      } else {
        return "";
      }
    });
  }
  let text =
    ">AT1G22840.1_532|1|training\r\nAGATGAGGCTTTTTTACTTTGCTATATTCTTTTGCCAAATAAAATCTCAAACTTTTTTTGTTTATCATCAATTACGTTCTTGGTGGGAATTTGGCTGTAAT\r\n>AT1G44000.1_976|1|training\r\nGATTCGACATAAGTCTATCTTCCATACCTTATTTACGTTTCTTCTGTGAGACAAAGTTGTACATTCTCCTGTGTTTTTTTTTGCAAATGATGTAGATTTCT\r\n>AT1G09770.1_2698|1|training\r\nACTGGAGAGGAAGAGGACATAGCCATAGCCATGGAAGCTTCTGCATAAAAACTTGAGTTTTGTATTGCTTACAAGTTTTAAGGAGACGTAGCTTGACTTTG\r\n>AT1G09645.1_586|1|training\r\nACAAAGGCCTCATGTTTGTTTGTGTTCGTTTGTCTGAGCATGTAGGTGGAACTTATCACTTATGGGTATTTAAATTTGAAGTATATATATACGCATACTTT\r\n>AT1G22850.1_1097|1|training\r\nATGCTATAAAGGATATTGATGATGATGAGAAGAGAGATGCAAAGTAGGAAACAAGCCAGCGATTGGATAATGGTTTTGACTCTCTAGGATTTGTAAAACGC\r\n>AT1G74960.2_2112|1|training\r\nGAGCTAAGCTAAGTTTCTTAGGATCAAGATCTGATGAGCCAAAGACTTGGACAGGAGCTAAAACGTGCTAGAGATATCAGAGTTTGGATTCGCCATTAAAA\r\n>AT1G77440.1_812|1|training\r\nCCGGTTATGTAGAAGCTCTCGTCCCATAGTAACTATGTTCCTTCTCTGAAACTGGATATTGTGGTTCGTTCTCTCGGATGTTTTATTTGCTATTGATAGAG\r\n>AT1G43900.1_1137|1|training\r\nGCGACAATATCACTTGCATTGTTGTACGATTCGAGGTTTCTTGAGCAAGAACCAAATTCATATTGTTCTTGTTCTATGAATGTACCATCTTCAGCTGTTGA\r\n>AT1G13320.1_1869|1|training\r\nTCCAATCTATTGACAATGTGATGATGTCTAGCTAAAAAAAGGTAAAGAAGACAGCAACGAATTGTGTTTGGTTCTCATGAGATTTTGTAAACGATACTTTG\r\n>AT1G76010.1_1331|1|training\r\nCTTGTTCTCTCACTTTCTTTCTATGTTTGCTTCTTCTGTCCATCAAGAAGACATGTTTGCCATAAGTGTATCTCATTCCCCTTCTTTTTTTTTTACTATCC\r\n>AT1G17440.1_2276|1|training\r\nGGTTGCAGGAGTTTACACATCTATGGAGAGTTGAAGGCACAAGTAGTGAAACTGTATGTATTATATATAAAATTCATGAGTCTTATAGGCAATCAAATAAT\r\n>AT1G12800.1_2517|1|training\r\nTGAATGAATCCACTATTTTTTTGTATTCTTGAAAGTGGTATCATTCGAAGACTTATACCAAGTCTACAACATCAATACATGATTTCTAATGTAATACTTCC\r\n>AT1G79230.1_1407|1|training\r\nTTAATCATAATCCTGGCTTTAAATTTGCCTCAACCCTCAAGCCGAAGAGGACTGTATCTATAGAACTTGGAACTTTTCCTTTTCGTTTCTGGATTCATCTT\r\n>AT1G77590.1_2324|1|training\r\nTTTCTTCTTCCTTTACTTTTTTTTTTTTTACGTCTCGATGCATTCGAAAGACTTAACAGATGCACAAAAACTTAATTCTAAGAATAGTTATCTCTTTTCTC\r\n>AT1G17340.1_2691|1|training\r\nCCTTGCACAGGAAGGTAACGGTGGTTACTTGGCAGGTACGGCAGGGTTGAACAGAGTCGTAATAACAGGAAAAGCACAGAATAACAGTTACATCTTGTAAA\r\n>AT1G16020.1_1965|1|training\r\nAGTTGGCCTGTAGATATGTAACAATGATATTCCACGTTGGATCAGTGCAAACAAATCCTTTTTTGTGCGGAGGAAAGCATCTTTCTCGTGGGTCTTAATCC\r\n>AT1G21170.1_3274|1|training\r\nGTCACAACCAATGGGTTCTCCGGTTCAAGCCAGACCCAGACGAAGATAAGACTTCTCTTCTCCATTGTTACTATGCTCGAAGCGTGTTGGTGATCATGACA\r\n>AT1G09280.1_1810|1|training\r\nTCTCCTTATATTGATGAGATTAAAGCTTTCCTTTACCAATTCATTTGAGGACTTTATTAACAAGACAAGAAGACTCTTTTGCAATCAAATATTTCTTGTAC\r\n>AT1G49760.1_2355|1|training\r\nGTTTATATACACTGTAAAAGTGTTTATTTTGTTCTTTTGGAGAATCAGAAACAGAGTTGTTCTTGAAAGTTTTGGATTTTTGAGTTTTTGTTTTGGGCGAG\r\n>AT1G09140.1_1094|1|training\r\nTGGTCTTCTTGTATGGGACGACCAATATGTCTTTCTAGTTTTAGTTGTGAACCTGGAATTGGTCTGTTATTGTGTCATTAAAAAGCCGGAAACTCTGTCTC\r\n>AT1G77610.1_1401|1|training\r\nATTGACACAAGGGGTGTTGAATTTTTACTAAATATGCATTTTACTCAAAAACCTTAGTAGAGAAAAGTTACATTTTTTTTTTTCGTTTTGATTTGAGCTCG\r\n>AT1G59750.1_2337|1|training\r\nAATGTACTTGCCACGTAGGAAATATGAAAGCAGAAGCAAGAGATCGTTAGACAATATGAAAGTTGAGATGTCTGTGTATAGCAATGAAGTTTTATGTCTTC\r\n>AT1G53760.1_1028|1|training\r\nATATCGCAATCTAGTCTAACTCTTTTGGCATTTTAGGCTTCTTTTTTAGAACATAATTTTAGCTGTTTGAAGCTATAACTTACGCTCCAATTCTTTTTTTT\r\n>AT1G23290.1_511|1|training\r\nTAGTTTTTTTTTTCAATTCAGTCTCTTTTTAATTTATTTCATGTTATTGAACTCAGCTTTGTTGGATTTTGGAATCAGAGATCTTTTAATCTATGGTATTG\r\n>AT1G61030.1_2703|1|training\r\nCACACTTTGGGTTTGCTCCACACTTATAGTTAGTGGTCTCACACAATGGAACATGTTACACGTATAATATGGACACAAATAGAGTATCTTTTAGTTCTTTC\r\n>AT1G03160.1_2771|1|training\r\nTTGCTACAAGTTGATATTGATAACCTTCATGTATCACGAGACGAGATGAGACTTTAGCTATTCCAACACAATGTCGGGTTTTCCCTTCTTGACATTGTTCA\r\n>AT1G03330.1_574|1|training\r\nAGAAGAGAAGCTAGGGGTGGCTGATTCTGAAATATCTTTGTATCTCCAAAACTTGAATACTTTTCATTCGGCGTAATGGCTTTATAATGAATATTTCCCTG\r\n>AT1G63290.1_805|1|training\r\nTGAGCCAAGGTCTTAAGCTAATACTTTTTTATTTCTTTGAAATGGAATAAACCTTAGATCTTAGTTACTTGTTATACAATTAAAATGTGTCTGAGAGCTTT\r\n>AT1G62020.1_3861|1|training\r\nGATTTCATAATCAATACAGAGATGCTCTATTAACAGAATAAGAGTGTTGAACTTTTGGTGTTTTTGTGATTGTGTACTTACCAATCAGGTTTGAGGATTTT\r\n>AT1G34550.1_2447|1|training\r\nCGAAAACAATGTGAGGTGATTTGTAGATTTAGGCGGCGTTAAGAGTTGAAACTTTGAAAGAAGAAGAAAAGGGGCTTGATTAGATTCATGAAAGGGTTCCT\r\n>AT1G48050.1_2064|1|training\r\nGCAGCGGACAGTGATATAGTAGACGAGAACGCTGGGGATTTCATCGTTAAACAAGAGTCAATGCTCGAGAGCTAACAAAGTCTTCGCTATAACTGATATTG\r\n>AT1G04410.1_1241|1|training\r\nAGCCTTTCAGGGCTTTGTCCGAATAAGAAGTGTGTTTGAAAGATCTCCAAACACTGTTTTATAACCTCTTTGGTCTCTTTGATGAGTATTGTCCCTGGTCT\r\n>AT1G04430.1_2156|1|training\r\nAGAAGAAACTTTGGCTCACCAGTGAAAGCCTTAGGGACAGCGAGTAAAAAACATATCAAAAGCAAAGAGAGAGAAATTGTTTTATCCCACAAAGTTTTTAT\r\n>AT1G77180.1_2121|1|training\r\nTAACTGATCTTTGATTTCAATATATAACTTGTTATTTTGGATCTGTTAAAACAGTTTGCTTTGGATTATCAGTATTTATGTTGTTGTGAGTCTCTTAAACT\r\n>AT1G32130.1_1785|1|training\r\nCTCTTCTATATATGCTTTGCTTTGAGCCTCTAATGTAATGGGAAGTGAAAACACTTTGTTCGTCACTTCTTTCTTCAGAGCATAAAATATTATGATAATCA\r\n>AT1G66240.1_431|1|training\r\nTTTTTATTTTCTTCTTCTGTTGCTTGTGACTTGTGGCTGAGTGTATTGGAACTATAGATGATACAACACACTTTTGAGTGAATAAATATGCACTGGGGCAT\r\n>AT1G28490.1_874|1|training\r\nTGCTCGTCTTGTTCATCATCCTATTCGTTCTTGTCTTCTTGACCTAAAGAACAGAGCCGCGGGATCTTATAGATGGGAGTTTAATGTCTTACATTATCATG\r\n>AT1G20830.1_1124|1|training\r\nCTAATTGTAAATACAGTTTTCCCTCGAGAGTCATACTTGCGTTCCAAGAAACTGGAGATTTTCTTTGTAGTAGATCACACTTACCTAAATCTATGTTTTTC\r\n>AT1G09870.1_1583|1|training\r\nGCTCTAGTTACTACACAGCTCTTCTTACATACTGGCTGATTACAGTTTGAACCTGAAATCACACAGAGCATTGTTGTCTGTTTTTTTTTTTGTCCCCTTGC\r\n>AT1G80210.1_1435|1|training\r\nTGTATGTTTCTATTTGGATATTTGTTTTCTTACAACTGTATCATAGGCAGACATCTGTTCTTAGTTTACTCATCTGTAGCATTATTGGGGTTTTTTCATTT\r\n>AT1G74640.1_1181|1|training\r\nAAGAGTATCCTTCTCTTGTTGCTCAAGAGCTCTACAACTTCTTGCAAGAGACTTTTGCTAAATGTTAGATAGATTAAAGCTCACGTATACAGCCAGGCCCA\r\n>AT1G29990.1_622|1|training\r\nGGGTGATTGATGTCTCTTTGTGTCACTAATCTTTTTTTGTTGACAACTAGACTTAAGTGTGTAACTTATACATGATCTTGTCGCCCTTTATGAAGTTATGA\r\n>AT1G54110.1_780|1|training\r\nCATGGTTGTCATGTTGATCCGAGTCACATAGAAAATGGTTCCTAGTGTAAACCAAATTAGCGACATGTAAAGATTATTTCAGTCTCTATATCATACAATTT\r\n>AT1G32400.1_1257|1|training\r\nTGATGACTCTAGCATTTGAGATCTCTAATCAACCTAGTCACGGTCTCAAAACTCATTTGTTGTGTCTGTGTAGTCTTTTGTAAGGATTCACCATTATGAAT\r\n>AT1G29070.1_641|1|training\r\nCTGTAATCTTGTTTCATGTGCTTTTTTTCCACCAGAAGATACAATGAGAAACATGGTTCGTTGAGCTCTTTTCTGCGTTTTAACTCTCTTGCATCCTTGAT\r\n>AT1G29880.1_2239|1|training\r\nTCTGCTGCTGCAGACGAGTAGCTAGCTCCTTGTTTTTTTCCGAATTAAAAACCAAAGTGTTAAATTAATTGTTGCTGAATCTACTCATTTTTAATGTTTTG\r\n>AT1G57680.1_1739|1|training\r\nTGAGAATATGTTTGCGCAAAAAAAGGCATAATTTCAGTTTTGTGGCAAAGACACTTTGACTGTAAAGGAGGGTTTAAGGGGGTTTACTCTTGTGAGGGTTT\r\n>AT1G57720.1_1497|1|training\r\nTACCTTCTAGAGAGTCCTTACCACCTTTTGAATCGTACTCGGGTTTAAGAACTAGTTGCTTCTCAATGTTATTTTGACAGAATATTGTTCTTAAATACATT\r\n>AT1G79920.1_2720|1|training\r\nAGAGCGAGATGGTGTTGTTGTATCGATTTTGTTTTAATTTACCTAGTGGAACCACTTTTTGTAGTTTCGCTATTATCCCCCAAACGATTCTATATTTAGTT\r\n>AT1G55110.1_1478|1|training\r\nCAACAACAACAACATAGCCACCAAGATTAATATATTATATCTGTATAGAGACTCTTTCTATAAAATTAGTTTGAAATATATGTTGAAAGGAGAATTATCAC\r\n>AT1G21600.1_1254|1|training\r\nGATGAATATGGGCCTCTAGAAAAAAGTGTGTAGATGCAATAGTTTGATGGACTAACATTCAATGACTAGAGAAGCTAGCTTATTTGCAAGTTTTGAGGTGT\r\n>AT1G31180.1_1288|1|training\r\nGTGTAGCCCTTGGTTTTACTGTTACTTTTTTGCTAATACATGTATTAGAAACTGTATTCTTGTAGCTTTTATAATAATAAAATATTTGGGATCGATTCTGC\r\n>AT1G04950.1_1995|1|training\r\nAGGGATTTCAAAGTCCTTAGGAGCCTGCAGAGTGGGTTGAGTTGAATTGAACCGGTTGCAATGTATATATTAAGAGAATTTTAATGATTCCGTAGTGGACT\r\n>AT1G73660.1_3854|1|training\r\nGATGTTCATGTTCATGCGTAATTTCCTCTATTTTGTTTTCCAATATTGAAACTGTACAAAGAGAGAAAGAAAAAACAATTGACAAACTCGTCGAAACGTTG\r\n>AT1G65000.1_493|1|training\r\nTTAGGAGTAAAAGACTTAGCTTGTGATCTCTCTGCTGGGTACTGTCTTGAACCACTTCTTGCATTGCACACAGCTACAGAGTGAGCTGTTGTGTTACAGCT\r\n>AT1G79390.1_531|1|training\r\nTCGATACAAAAATGGCGTGTTTCCTGGCCGTAATATCTTTTGTTTTTGAAACCGGCATCTAGCGACACAACTTTTGTGCTATGCAAACGGCTACAATGTCA\r\n>AT1G18360.1_1436|1|training\r\nATGTAGCACAGTTCCTTACTCCTTAGGTAATATAGAGGGATATGCGAAAGACATAATCAATAGTTCCTCTGTTTCTGTCGATTGATCTCGACACTATTTTG\r\n>AT1G31020.1_632|1|training\r\nGATGTGGTGAGGCTGAAGAGTGTCATGGAACAACTCTACAAGTGAGAGAGACTCTTGACTTCTGTACACTACATTGCTTTGAGTTGTGATTATCTTGTGCT\r\n>AT1G57860.1_479|1|training\r\nAGCCTAAAGGTCCTAAACCGGGTTTCATGGTTGAAGGTATGACATTGGAGACTGTCACTCCCATTCCTTACGATGTTGTCAACGATCTCAAGGGTGGTTAT\r\n>AT1G01820.1_988|1|training\r\nGACTACTTTAATGTTTGTGTTAGATTCTATGGTATATAAGATAATGATAAACATTGCAGTCTCTGTAGAATAATAAGAACAGATAAGCATTACGAGGTGTT\r\n>AT1G02130.1_746|1|training\r\nCTCAACTTGATTGACGTGACCAGCCTAGCAATATCCTTTCCAATCTTAGAACACGTGTTCCTTCTTTTGACTAGGCTCCAATTCACTACTACTTGGTTTTT\r\n>AT1G51510.1_801|1|training\r\nGGATTCCCTCTCTTATCTGTAAGGTACTGATGCAAGACGCTGAGTGTTGAACAAATTTTTTTCTGGGGTTTTTGTAGGGTTTGGCTGCTTTTGCATTGGTT\r\n>AT1G73760.1_1106|1|training\r\nTGGGCACAGGTTCCATATCGACTGTGTGAATCAATGGCTTGTGAGGAAGAACTCTTGTCCGGTCTGTAAAACGATGGCGTACAATAAGTCTTAGTTAGATA\r\n>AT1G78140.1_1126|1|training\r\nAACTTCACTCGTGTTAGAAACGGGCCATTTATAATGCTATCTGCAACAAAACCCAGCTAAGCTCACCCTCTTTAAAGTATATATACTTTTCTGTAAAAAAT\r\n>AT1G10630.1_727|1|training\r\nGGGGATTGAAGCTTTCTCTCCGGAGTCGACTTGATTTCTTGTGGTTTAAGACCTGCTCGATTTGTTTCATGTTTTACTGTCACCGTTTCTCCTTTTTGCTT\r\n>AT1G01960.1_191|1|training\r\nGAAAATTCCTCTCCTGTTGCCGACTCTGAATCTGGATCCTCCATTCCTGGACCACTTCACGACGGAGGAGCCGCCGAATACTCTCTCGCCGAGTCCGAGAT\r\n>AT1G01930.1_1841|1|training\r\nTAATTTCCAACTTTTTAGTGAGTTAGGTAAAAGAGGAGAAAGTTTGAAAAACAAGAAGTGAGTATCATCATTAAAGTGCACAACATTACCGACTCAATTAT\r\n>AT1G02080.1_7282|1|training\r\nTGGCCTGAAGCCTGTCGACGAGGGAATGGTTTCGGGAGGTTGGGTCTCAGACAATTCTCACTAGCTCTTTAGCTTTCAACTTGTATATATGTATGCGTATT\r\n>AT1G51590.1_1872|1|training\r\nCTATAGCACTACGCCAGAGGAAGTTTGGTCATCAGATTAACGTTTAGTAGACAGTTTCTGCTCAAATGGAATTTGATATTATTATATATTACCACAAAGTT\r\n>AT1G33810.1_498|1|training\r\nAAGCTCGCCGTGTTCGTTGAAATATGACCATATTTCAATCTTGTGAATGGACCCAGCACTGTTAGATTGATTAAAATATGTCCTCAAAGAGATGTTTTGTA\r\n>AT1G80950.1_1345|1|training\r\nTTAGCGACAAAAGGATATATCACGCAACTCTCAATGGTAATCTTAGTCAAACCCGTGATTTCCATCAGAAAGAAGAATGAAATTTTCTGGCCTGACAATGT\r\n>AT1G08370.1_1375|1|training\r\nAGAATGTGTAGTTAAAATGTAGTTTTGTTCCCTCTGAAAGTGTTGTTGGAACCTTATAAGATACTGCACTGCCCCCTTTGTTTAACTCTTGGAATTACTTT\r\n>AT1G05140.1_1421|1|training\r\nTTCTGGAATCATGCTTGTATTATTTCTCGGTTTATTTCTCATCGTAAAGGACACACTTAATCTTGATTTCATCAAAGAAATGTTGTAAGCTATTGAGGTAT\r\n>AT1G18800.1_922|1|training\r\nATGACGAAGAAGACGAAGTTGGTGAGGAATGATGGCAGGGATACCCAGAAACCACATTTGCTTACATGTCTTCTCTATAACAGAGTGTGTAAAGTTTTGTG\r\n>AT1G08190.1_3264|1|training\r\nCTGTAGTTCTCTAAAATATAGCAAAAAGAGAAAGGCGAGAGATGGAGAAAACATGTGTGCCAGAATTTGTGCCTTTGTATTATTTCCCGATGAGTGGCCAA\r\n>AT1G13950.1_642|1|training\r\nCTCATCGGAGATTATCTTGTTTTTGGGTGACTCCTATTTTGGATATTTAAACTTTTGTTAATAATGCCATCTTCTTCAACCTTTTCCTTCTAGATGGTTTT\r\n>AT1G69640.1_1107|1|training\r\nAGAAATGGATGATACTTTGTGTTATTGGAGGTGTAGTTTTAAAATCAGAAACAGAACTGGTTTTTTTGCGTTTTGCGTTTCTTCTCAAGAGCGAATTTAGC\r\n>AT1G18540.1_712|1|training\r\nGAGCTCAAGGTTTACCTTGGAGCCAGGTTCTCATTGAGTCAAGGAATGAAACCACATGAGCTTGTTTTCTAGATTTCGTATTGTTTCTCAAATTTTAAGAA\r\n>AT1G45180.1_2282|1|training\r\nTGGGTTCTAACCATTTGTCGAATCTTCAATACCATTGAAGCCTCATCAGAACACTGCAGGCAAGTTGGTGTCTGCTTTTGGGGTTGACTGAAGATAGGAAT\r\n>AT1G27695.1_370|1|training\r\nGTTAGAGACTGCCGATAAACGGGAGGAGGTGGTGGCTAACATGTCCAAAAACTCCACTTAAGCAGTCGTGTGCTTCAATACTCTGCTCGGATTGATTGTAA\r\n>AT1G27430.1_4553|1|training\r\nTTACATGTAAAGATTAGATTCTCATACTTAGGCGTATAGGTCCTTTTCGGACAGATTTCTTACATCACATAAGAGCACACGAAATGAAATAATAATGTTTT\r\n>AT1G69410.1_650|1|training\r\nTTTACAGAGGCTATGTATTATCAAGTTTGACAGAGTCAAATGTTATAAGAACAAAGTTTGGTCCTTTTTTTTGGTCTTCTTAGTATAATTTAAGCCCACAT\r\n>AT1G64740.1_1465|1|training\r\nTGGAGAAGGAGCGGAGGACGACGACGAAGAAGGCGATGAGTATTAGAAAGACACAAGAGTGTGTGTTCCCTTGTTTCTTTCTTGTGAAGTACAGTAATTAT\r\n>AT1G64850.1_626|1|training\r\nTGTCACCATAATAAATGTGTTTATAACTCAACTGCTACGAAAATATAGAAACAACGCACGGATTGGTTGAACGGTTGGATAATACTATTTTTTTCTGATTT\r\n>AT1G05070.1_804|1|training\r\nTTCAGGTTGCTTAGGATACCCAAGGATCAGCAAAAAGATCTTAGTTACAAACCACTCGTGTAATTGTTTGTGAATTGGATGCTAACAATATAGTGTCAACT\r\n>AT1G08580.1_444|1|training\r\nTGAAAAATCTGCTGATTGTATGCTAGAATGAGTGTCGTGTATACCTGTAAACCCATTTCTTCTAACGGATGATAGAGGTTTCTCAATGTCTGGTTAGATTC\r\n>AT1G79570.1_4178|1|training\r\nCAACTTCAACTCAATCCAAGCCATCAGCTCACAGGGCTTCCAAATGAAAAACCTTTCTTTTTCTTATGTGCAGTGAAAAGAGAACATAAGTCGATTACAAA\r\n>AT1G30270.1_1979|1|training\r\nGAAGTTAATACAAAAGGAAGCGTCAAGAAGTGGAGCAGAAGCAGTTTGAAACTATATTGGGGAATGGGGATTATTGATATTTTAATCATGTTTGATTCCAT\r\n>AT1G16720.1_1862|1|training\r\nAGACAAGGCGAACAACTATCTGACTCCGGCTTTATCTGTACTTGAGAAGAACACATGAGAAGAAGAATCATTGATTCCATTTTGTATATTGTACACATCTC\r\n>AT1G19140.2_1132|1|training\r\nACGGATTCTCCAATATTTTGAGTTGGGATTTACTATAATAATGAGATTAGACTTATATGAGTTGAAGTGAAGGCATATGAACTAATATATTATCTTCTACG\r\n>AT1G47420.1_950|1|training\r\nTATTGCGTTATTTTGTCTTAGCACATAATAAAGGTCAATCTGACCAAAAGACATATCAGGTGAGTCTGTTCATTGTTTCCTCCAAATGAAGCTTTAAAATT\r\n>AT1G75340.1_1513|1|training\r\nATCTCAGATTTGTGACCAATGTAGTTTCTCCACAAAATCCAAAGTTTTGAACCTTAACAATAATTTCAATGCAGATAACAGAAACTATAAACAAGAGAATT\r\n>AT1G19120.1_688|1|training\r\nTAATGTTAGTTGATGTGTGTATGTGTGGATGACATTGATGAATCCTCAGAACTTAGTCGTTGCAGATCCTCTGCTCTGTTTATGGAATGAAATTGTTGAGC\r\n>AT1G30450.1_3238|1|training\r\nCATTTCCTCTCCTGGATTATATCTCCCGACTTTTGGAAGATTTTGCTAAAACTACCTATGGTTTTTACCCGTATTATTTCACCGCTCACTAATTTTTCATG\r\n>AT1G19600.1_1195|1|training\r\nTTCCTGACATCCACAACTGATGATATCACCATCAGATTGTAGAATTTCAAACAATTTCGTTGAAGGGCCGGTTCTGATTCAAGCAGCTCTTAGCATTATGT\r\n>AT1G14320.1_828|1|training\r\nAATCTTTTTACTTATCGTTATCTCTGGTGTTGTTTTAAGTTTTTAGTTGGACACAATCAGTATTCTGAATCTTTTTGTGACTCTTTTGTTTAAGCTCTGAA\r\n>AT1G17050.1_1488|1|training\r\nGTTTAATCTTGAAAGGATTGATTAGTTTCAAAGGGTATTTGGCAGAGGAAACTGTAACAACACTCTTTACTTGTTCAAAACTTCAAACACAGATTTTTTTT\r\n>AT1G69295.1_1510|1|training\r\nTCATGGTTGATAGAGTCATCTTTTTTTTCACTCGTCTTTCTAGGATTTGGACTTAGGTTGGCCGAGAGACGTAATGCTGGTAGTAGCTAGTATTTTGGGTT\r\n>AT1G07940.1_1683|1|training\r\nTGGCACTCGAGCTTCCTGTTTATTTCTTTTGTTTTGTGTTATGATTTTGAACCTTTTTGGATATTCGGTTATATGATATTTGTGTCATTCCTGCGGATATT\r\n>AT1G78670.1_1199|1|training\r\nGTTTATATTTTCACGTAACAAAGATCCCTTCTCTGTGTGTTTTCGCCAAAACATAGCAATTTATATTAGTTACTAAGAGCAATACAGTGTTTCTCCTTATC\r\n>AT4G38780.1_224|0|training\r\nTGGATGCAGCTAAATTCCAAACGGGATCATGGTGATATGTCATCAAAGAAACATCGACTTGATAAACGTGTATATCTTGGAGCACTTAAGTTCGTTCCTCA\r\n>AT4G31140.1_594|0|training\r\nAGGTGAAACTTTTCGAGGCCGACTCTGCGATTCTCAAAGCTTTAAGTCGGACAGGGATTCAAGTTATGGTCGGAATCCCTAACGACTTGCTTGCTCCTTTA\r\n>AT4G27300.1_130|0|training\r\nCATCACTCCAAAAGAATTCCTTAAGGATGGAGATACCCTTAGTTCTCCAGACCAGGTTTTCCAACTTGGGTTCTTTAGTCTTGACCAAGAAGAGCAACCTC\r\n>AT4G37790.1_784|0|training\r\nAACTAAAGCAAACAGAAGTGGATTGTGAGTTTTTGAAGAAATGTTGCGAGACTTTAACGGATGAGAATAGAAGGCTTCAAAAAGAGCTTCAAGACCTTAAG\r\n>AT4G39720.1_561|0|training\r\nGTTTACCGGAATCCCAGCTCCACCGCTATTCAACAACAACTCCATCGTGAACACCACGCGCCTCAACACTTTCCTCGGCTTGTCTTCTTCTTCGCCAAACA\r\n>AT4G18700.1_1617|0|training\r\nAAAGGAGGAGATAAAACAGAGTATGAAGATTTCTGTAACAATGAATTGAAACCCAAGTTGCAAAACTTGACAGCTGATGATGTAGTAGCTGAGCCTGTCGC\r\n>AT4G13400.1_659|0|training\r\nGGGCTAATGGTAGCTTACCACTGTGATCAATATGTGTCAAAGGGTATAAAACAACATGAAAAGCAAAATCTTGAAAAGATACTACTTGGCTCTCGGTGTCA\r\n>AT4G08109.1_3895|0|training\r\nAGAACAGCTTATGTTCTACGACCTTGTTAACAAAAGCTTCGACACGAAGGACATGCTGGAAGAAGCATATGTAGTTGAAGAAGAAAAGTTGTCCTGGTATG\r\n>AT4G08109.1_4172|0|training\r\nTAGGACATTGCCATGGATCCACCTATGGAGGGCATTTTGCAACCTTCAAGACTGCTCAGAAAATTCTGCAAGCAGGTCTATGGTGGCCCACAATGTTTACG\r\n>AT4G18530.1_370|0|training\r\nTTAAAAGAAACCTTTTTGAGAGGGTAAAAAAAGCTTCAATTTTCAGAGAAACACAAAAGGCAGAAACAGAGAAAAACAAATCATCTAATTCATGAAACAGG\r\n>AT4G38150.1_621|0|training\r\nCAAGGCTCATAAAATTGAAGACGCTAAGAGGATTTTCAGGAAAATGCAGAACAATGGGATTGCCCCTAATGCCTTCAGCTACGGTGTGTTGGTTCAGGGAT\r\n>AT4G23050.2_731|0|training\r\nAAGTAATGAGCATCAACAACAAGCTCGTAGTAATAATAGACATGAATCAAACTTGAGAAAACATCAGTGGCACCTCCCGAGGCCTCAGATCGCTGCAGCAT\r\n>AT4G03410.2_469|0|training\r\nCGGTAGGACTCGAAGCAACTGGTCCTATGGTCTAGTGGTCAGGACATTGGACTCTGAATCCAGTAACCCGAGTTCAAATCTCGGTAGGACCTTTGTTTTCG\r\n>AT4G03410.2_1081|0|training\r\nTTGCGGTTACTAAGCTTTTAACCATTGATCATGACTATTGGCAAGGTTGGACTCTCTACGAGATACTTAGGTATGCACCTGAACATAATTGGTTTGCGTAT\r\n>AT4G01593.1_583|0|training\r\nGATCTGAGGTTCTAAGAATCTAATTACAAAGTGAAAAAGACAGAATAGAGACCTCTGTAGGAGTCGGTCGATCGAAAGCCAACAGCCTCTGCAAAAGACGG\r\n>AT4G12020.2_3722|0|training\r\nAATCCAGAGAACCTTGTCGAGCTTAACTTGCCAAGTAGCTGTGCAAAGAAACTTTGGAAAGGAAAAAAGGCAAGGTTTTGTACAACCAATTCAAGTCTGGA\r\n>AT4G27010.2_115|0|training\r\nAACTCTCAGCGTCGCCGATATGTTTTGTCCTGTTAAACCCTAAAACTAAAACCCCGCGAAGAGAGAAGAGTTCTCTGTAGTGTTCTTTTGATGGCGGAATC\r\n>AT4G32820.2_2846|0|training\r\nAAAGTCAAATCCAGTATTAACTCCCCAGATGGTCTTGGACATGATATGGGACTGCCTGACAAATTATGCAGAAATGAAGTAAAATCATTTCTCGAAGAGGT\r\n>AT4G19990.2_2391|0|training\r\nCAATCAAGTTTCAGACCAGAAGCTATGTATGAAAGACTACAAGATATGGGACAATCAACTGTTAGACATCATCCTCAGCAACATTGCAATGCTTCGAAACA\r\n>AT5G08230.1_242|0|training\r\nTTTGTTACGCCTCCTGATATTCAACCCTTCACTAGCGAGACAAAGAAGAAACTGTCGGCAAGATGTCAAGGTAAAACAGTCAAGTACTTTTCCCAAGCCGT\r\n>AT5G08230.1_2553|0|training\r\nGTGCCACTGAGGCTGCGATTTCTCGAGATACTTTTGAGGGAATGATAGAGACTTTATCCAGAACTAAGGAAAGTATTAGACGTGCAACACGCGTTGCAATT\r\n>AT5G39260.1_693|0|training\r\nGAAGCAAAACCGCGTGGGTAGTAATGAGCAGATATTGGGGACAAAATTGGACTACTAATGTTAATCTAACCGGTCAAAGTGTATCATTAAGGGTTACAACG\r\n>AT5G56160.1_1914|0|training\r\nGAACTCGATCTCGACAAAACGAAATCAGTATTACATATAACATTAACAAAACAACTTCAGATTACAGAACAGCTTGAATCTCAAGACGAAGAACGAAGAAA\r\n>AT5G49530.1_1141|0|training\r\nTCAACGAACTATGCCGTGGGGGAAGCAGCAGAAACTCTGAATCGAAAGAAACATTAAAAAGGGTCTTGCTCTCCCTACCACTTAAAGAACGTGTGCAAAAG\r\n>AT5G16570.1_168|0|training\r\nATTGGTGGATCGGGCTTGGATATGAGAAGCAAAGCAAGGACTTTGCCTGGACCAGTGACGGATCCATCGCAGTTACCGAAATGGAACTACGACGGTTCAAG\r\n>AT5G44350.1_663|0|training\r\nACAAAGACAAAAACGCGATTGCCCGCGAGAAAATCGAAACTTTTGATGAAACTCGAGTTCCCAAAGCGATTCCATGTCCTGAGGAAACAGAGCATGTAGTA\r\n>AT5G16360.1_319|0|training\r\nAGTTTTGGACAAGATCATCGATATTTCAATACCAAATCATGGAAGAAGAGACAAAAAGTGTATTGATTGTGGAGATCAATCCAATCTCGGTGGTGTAATCT\r\n>AT5G63790.1_673|0|training\r\nGTATTTACCGGCGGCGGCTGAGAAACCGACGGAAAAGATGAGTACGTCGGACTCAAGATGCTCAAGTCACGTGATTTCACCGGACGTCACGTGTTCTGATA\r\n>AT5G17330.1_1736|0|training\r\nTAATTGCATTGATTTGGATATTTGAATGTTTCATTCCCCTTTATCGCTGAACCAAGTTTCATTTCCCTTTATTGCTGAAGTAAGTTTCATTTCCCTTTATT\r\n>AT5G61910.1_2393|0|training\r\nATTCTGCAACAGGAGATTGGAATGCAGTGCATCAGTCTTATTACCCTCAGACAGCAGATGCAACCACAACGTATTATCAAACATCTTAAAACGTTAAAGCA\r\n>AT5G65790.1_415|0|training\r\nTGCTGCACAATTGCCGGGAAGAACCGACAACGATATCAAAAACTATTGGAACACGAGGCTGAAGAAGAAGCTTCTGAACAAACAAAGGAAAGAGTTCCAAG\r\n>AT5G48800.1_593|0|training\r\nCTTGAGAGCATCGTATGCAAGAATCTTGAGATGTGTGTTCAAGTCTTGAAACAATCCGAGATTCTTCTCCCTCTTGCAGATGAACTGAATATCATAGGTAG\r\n>AT5G35450.1_2088|0|training\r\nAGATGCTAGAGTTGAGGTACCTTTCCCTACCTCTGGATATGCATGATAAAACCAAGTTGGAATTGGGTGATCTAGTGAACCTGGAGTACTTGTGGTGTTTC\r\n>AT5G61250.2_720|0|training\r\nCAACACTCAGGATTTCATGAACTACACAGTCTCAAAGGGTTATGCTATAGACTCGTGGGAGTTTGGTAATGAGCTTAGTGGAAGCGGGATTTGGGCAAGCG\r\n>AT5G04235.1_1160|0|training\r\nATGCTTGTGGATGAAGAGGGTGATGAACAGTTTTCAGAAGGATCCAAAGGACAGATTGCCATAAACTATTTTCGAGAGCTCTTTAGCAGCTCAAAGCCACA\r\n>AT5G04235.1_2912|0|training\r\nAACAGAGACGTTATGCTAAGAGTATCAGATCTGTTGGATCGTAACACGGGACACTGGGACGAAGATAGAGTGAGACATTTGTTTATTCGGGAAGATGCTGA\r\n>AT5G52750.1_354|0|training\r\nGTTAAACCACCTGAGAAAAAGCCTGAACCAGAGAAACCGGCTCCACCTAAACCAGCTCCAGCTCCAGCTAAACCGGCTGAAATTGTTGCCTGGCCGGTTCA\r\n>AT5G45380.1_461|0|training\r\nCGTCATACATCGGAATGGTTCAATACAGCGGGAAGAAACGTTAAGACAGGACTTATTGCAAGTGTCATTGTATCACAGTGGACATGGGCTGCGACCATACT\r\n>AT5G19600.1_1279|0|training\r\nATTTGACAACGGGGCCATTTTCAAAGACAGCAGTGAACTACAACGCGGGGACAAAGACACCGATGTCGAATGTAGTAATGGGCGTTTGCATGATGCTTGTG\r\n>AT5G44670.1_150|0|training\r\nGTGAAGAAGAACTCAAAAGATGGCTAAAGAGAGAGACCAAAACACTAAAGACAAAAACCTCCTCATCTGTTTCTTATGGAACTTCTCCGCCGAGCTTAAGC\r\n>AT5G49430.1_3226|0|training\r\nTGAACTTATGGGCTCTGACCCGGAGGGAAAGGAAAATAATGTTAAGGAAGACTCAAATCACCGTGGAAATGGTGTTACAGCACCTAGTTGTTTGGAATTGA\r\n>AT5G67110.1_739|0|training\r\nAGACAATGATGATGATCGGAATTCCTCTAGTACCTGCCAGACAGGAGTGAACAATGTTTTGAGTTTTAGCATTGGCCAGATTTCTATGTTCAGTTATAGTT\r\n>AT5G25350.1_1213|0|training\r\nGCTCGAAGCTGTTGGAAATGGTTGCCCTGATCTGAAGCATGTCTCTCTGAACAAATGCTTGCTTGTTTCTGGTAAAGGACTTGTCGCTTTGGCCAAATCTG\r\n>AT5G01715.1_1943|0|training\r\nTCTTCCAGCATTAGACTTTCAATGATAAATAGCTTTCTGAGTCTAAGAAAACATGAAACCTGTTTATACATCTTCTCTCATAAAAGTTAAATGTTTCCAGA\r\n>AT5G57210.1_1131|0|training\r\nTCTTTAGTTGATGCTTCTCTTCACAGCCATCTCGTTGAACTCGGTGTTGAACCGCAGTACTTTGCGCTTCGTTGGTTACGGGTTCTGTTTGGGCGAGAATT\r\n>AT5G06930.1_256|0|training\r\nAAGAAAGATCAGAAGCCGCGTAGTAGTAGTAGTAAAGGATCTGGTGTGAAACCGTTGAATGCGGCTCAGCTGGTTTCTAGAGTTTTAGATGCAACAACAGC\r\n>AT5G06930.1_1429|0|training\r\nCCTCAAGGAGTAGACTCGACGATGGGTGAAATGATCGGTAATTTTTCAGAACCAGCAACATGTGACCGGTTACAAGAGAGCTTTTCTGTTAACCTATGGAA\r\n>AT5G29890.2_813|0|training\r\nGTTATTTCTCGAGTCTTTTTAGTGTCTTTTCAGGTATCCTATGCATTGGGACAACAATGGAGATGAGGAGACATTTTGGAGCAAAAACTAAGAAAAAGGAA\r\n>AT5G57590.1_1360|0|training\r\nTACACTGCTGCTAGGTTTGGGCATGTTATGTTCCCTGAGAATGTATATGAACCTGCCTTGAAGTGCGCTGAGCTGTTATTAGATGGAGTGGGAAAAGGCTG\r\n>AT5G57590.1_2255|0|training\r\nTGGGTTGCGCAACAGCCGCCAAAGCCATCCAATGGTTCAAAGATCCAGAGACTAACCACAACATCACTTCACAAGGAAAAACTTTAAGAGAGCTGTGGGAC\r\n>AT5G07570.1_2267|0|training\r\nAATATCGATCCATCAAGTGCACTTGCATCTGATGGAGGTCCACCTGATGAACCTGCATCTGCTGAAGGTTCACCCGATGTAGGCATATTTGGTATAAGTCC\r\n>AT5G22730.1_1506|0|training\r\nATTCAACGGAAGGCCTGCTAAAATGGAAGTAGCAAGGTACTTTTTAGAAAACTCTGGAGTTCTCCAAAAACTTGTTCTGCATTTGAGGTGTTCCACGCATG\r\n>AT5G07460.1_146|0|training\r\nCGAGGTCTCATCATCAAACAATACACTTAACAATGGATTCTTCTCTGAAAACTCAGGAACCTCAAGTAGTGGAAACTTCTCCTTCTCCGGTAGCTCAGGAG\r\n>AT5G51630.1_3331|0|training\r\nCTGCTATTTCAGAGACAAATGTGTCGAGCATAGTGTCCAGTTTTCCTGGGACTCGAATAAGATGGATCACCTGCTTATGATCAACTTTCGGCTCCCTACAA\r\n>AT5G24340.1_1081|0|training\r\nGATGGCTGCCCTAAATTTCTATTGGATGTGATGGTTGAAGGTTTGGCGAAACATCTACGTTGTGTGGGGATTGATGCTGCAATCCCACACTCAAAGAAGCC\r\n>AT5G56930.1_1859|0|training\r\nAAGACTACGCCTAGCTCACACATTCAAAGTTCTCTACTCTCAGCCATGAAACTCGCTGCAGAATTCGAATCCGCTAAAGTTGAACGAGGCAACAATGATCC\r\n>AT5G51770.1_1091|0|training\r\nGGGAAGGAGTATGTGATGCAATGGATTGGTTCTGAGGTGAAGGAAGAGAGACAGAGTAGTGATTGGATTGCTGAGACGGCGGAAGGCGGTAAGAAAGTTGA\r\n>AT5G51680.1_285|0|training\r\nTATAAATAAAGAGAACAACGTAAGAGATACGAACAAATGTCTGATATGGAACCAAAAGAAACAAAACCACCTCGAAAACAATTGAGACAGCCTCCTTCTGT\r\n>AT5G51680.1_797|0|training\r\nTGATGCAAGCAGTGACTCCTTCAGCTCTGTGCCGTCTCTATTAGCAACAAACCGCTCGGTTTCGATATCCGGTGCTGTTGCGGTGGATGAATTTGATGACA\r\n>AT5G42010.1_208|0|training\r\nCCGTAGACAAAAGTTTTTTCAATCTATGGGTTTTAGTTTCAAAAAACGAGACTTTGATCTTGATCTTGATCTGTTGGGAGACTCTAGTTCCGACCATATTC\r\n>AT5G42010.1_1885|0|training\r\nTATCATAGCAGATTTGGAAAAAAGTTTTGCTCATTTCCCTGTTCCCTTGGACTATTTCTCTCCAATGAAAGGAGCAACAACATGGCCGGAAGAGAAGCTTG\r\n>AT5G13530.1_211|0|training\r\nGTGTCGCCACGTGTCTGTTGTTGGGAACTCTGTTCAGGGTCTCAGGAAGAACTACGCTATGCTTGCTCTCATTCACGCCGCATCCGGCGGCGCTAACTTCG\r\n>AT5G44020.1_138|0|training\r\nGTGACTGGAACATCCTGAGCCAGCTCAAAGGAACCACAACCACCACGAAGACTAGCCAAACCGGCGTCACATCTTTGAAAGCTCCCAACCTAAACGGATAC\r\n>AT5G56730.1_726|0|training\r\nATTTATGCAATATGGCAGTTGTGGCTGTTGGAGATTTTCCAGATACAAAGACTGTAGTTGATTTGATAAAGACACATTTTGAGGATAAAAGATCAAGTAGC\r\n>AT5G17250.1_915|0|training\r\nTAGTAATGGGTGACCATGGGCAGACATTAAATGGGGATCATGGCGGAGGGACTGCAGAAGAGGTAGAAACAACCATGTTTGCCATGAGTACAAAGAAGCAC\r\n>AT5G17250.1_1906|0|training\r\nTTCTCAGTTTATGAGTAGCTCACCATCGTGGATGCTAGGGATAGCTCCAGACCATCCAGCATTGACATATGCGATTGAAATTGCACCAATTCTGTCAGTGG\r\n>AT5G65970.1_1277|0|training\r\nTTTGGGCTAAAATCTTGCTTTCACACGGATTTCAAACTAGTCATCGTAAAACTCTCTCTAGGCGTTGGAGCTTTGATTTTGTGCAGCTACATCACACTTCC\r\n>AT5G06670.1_1283|0|training\r\nAAGTACCAATACGAGATTCGCCAACTCAAGGAGGAGCTGGAACAGCTTAAACAAGGAATTAAACCAGTTTCTCAGCTAAAGGATATCAGTGGAGATGATAT\r\n>AT5G16760.1_1013|0|training\r\nCCGTTAAGTTTCTTGACAGATCTAGCAAAGGCCATGAGGGAATCAATGGGACTCAATCTCTTTAACTTCGACGTGATTAGGGATGCCAAAGATGCTAATAG\r\n>AT5G53320.1_373|0|training\r\nGGTTAAGCAATCTTCGGTTTCTCATTCTTAGTTCCAACAACATCTCTGGAACTTTTCCTACAACTTTACAAGCTTTGAAGAACTTGACAGAGCTTAAACTC\r\n>AT5G09680.1_540|0|training\r\nGAGAGTCAAACAAGAGGCTTATTCCAATGGATGAAGTAAAGAAACACCGAACAGGAGATTCGATGTGGACTGTTTTGAAAGGTCGTGTATACAACATATCG\r\n>AT5G24800.1_168|0|training\r\nACAAGAGTATCTCACTACAAGCCCTCTAGACCCTTGTTTCGACCTCATGAACCGGGATTACACTTGTGAGTTAAGAGATAGTCTTTTGTGGTCTGAGGGAT\r\n>AT5G65160.1_2032|0|training\r\nCGTAGTGGACAAGACTCTTGAGAATTTTTCCGGTGAATAAAAACCAGTAAACAACCGTGAGGGATATATGGATTGAGAAAAGAAAACAGCCGGAATATTCC\r\n>AT5G14710.1_197|0|training\r\nCACTAATTTTCCTGTGCGCCATAGAAAGGTCTCGTTTGAAAGTAAGGGAAACAAGACAGAGATTGTGATCTGCAGCTATGAAGATCATATCCTTATCATAG\r\n>AT5G14710.1_202|0|training\r\nATTTTCCTGTGCGCCATAGAAAGGTCTCGTTTGAAAGTAAGGGAAACAAGACAGAGATTGTGATCTGCAGCTATGAAGATCATATCCTTATCATAGCAACA\r\n>AT5G14310.1_1149|0|training\r\nGGTGGGAACATAGCAGACTATGTAGCTCGGAAAGCAGTGGAAGCTGGGAAACTTCTAGAACCGGTGAAAGTTGTTGCACAGGTTCTAATGTACCCCTTTTT\r\n>AT5G15570.1_715|0|training\r\nATTCCTTTCGTTTATTCTCTTCCCCGTTTCCCTTTTAACAGAGGAAAAAGACCAGCTCCTAGCTTTTCCGATATTGGAGTAGAGCCACCAGATGAGCATAT\r\n>AT5G59450.1_1114|0|training\r\nTGTCCCATCTATGTAACTGATTACTTCGCTGCGAACAAATCGATTTACGAACTTGCTATGAAAGCAACTAAGCTTCACATAGTTGATTTTGGAGTTCTCTA\r\n>AT5G43880.1_321|0|training\r\nCTGTTTGATTTTGGAACTGTTGGTAATGGAAAGAAACTGCTCACTGAGAAACCCCATTTTGATCATGGGTCTATCAAGGGGAATCAATTTGATCAGATAGA\r\n>AT5G39880.1_400|0|training\r\nTCCCATTGTAGATGTTTTAGGAATTGCCAAGACCAGATACACCCTGATGAACAAGGCAATTCTTGCTGCGCAAGCTAGTGTTGGCGGTAAAGTCAATAAGA\r\n>AT5G24010.1_1643|0|training\r\nAGTTATCGGAGTTGGCGGATTCGGGATGGTTTTTAGAGGGTCTCTTAAAGACAACACCAAAGTAGCTGTGAAGAGAGGCTCTCCTGGTTCAAGACAGGGCT\r\n>AT5G44870.1_1040|0|training\r\nGAAGAGCTGTTGAAGGATACTAATCTCAACATAGGATATACAACGAATGAACATGAGTTTTGTAAGGATGTTCTTCTCCTAAAGAAAGTTTTTCTTGTCAT\r\n>AT5G44870.1_2998|0|training\r\nCTACGCGAAATGGAAATGCCACCGACTTGCAGTTGAATGCTACGAACAGGACATAGTTTCTGGAGCTTTTTTCAACACTTGCTATCCTGGATATATAGTCC\r\n>AT5G59530.1_413|0|training\r\nAGAAGATCCTGAGGTCAAGAAATCATACTACTCGCTTGATTTCACCAAGAACAAATTTGCATACAGTAGTAATTTCGATCTATATAGTTCTTCGCCGTCTC\r\n>AT5G59080.1_368|0|training\r\nCAAACATGGCTCACAAGCTCAACGTAGAGAATCTTTAAATGCTCAAGAAGACAGAGTTGAGCCATGTCATCTAAGCTCTTCTCTTTACTACGGTGGTCAAG\r\n>AT5G15330.1_146|0|training\r\nGCCTTTTCTACATGAAATTCGGCAAAGAGTTTCGTACTCACCTCGAAGAAACTTTACCAGAGTGGAGAGACAAGTTCCTTTGCTATAAACCTTTAAAAAAG\r\n>AT5G53900.2_681|0|training\r\nGCTTCTGATAAATGTCACAAGTGGGTTTTCAAAGAACCATCTGAATCTGAACCAAATCTTGCTAATTACTGGCAAAGTTCTTTTGATGCTCTTCCTCCAGA\r\n>AT5G57250.1_1665|0|training\r\nTTATCGAGCTGTGGGAGAAAGGTTTATATTTGGACATCCATACATCTCGGACCTTGTTACATTCAATCCATGCTAACGGAGGTGACAAAGGAATACTCGGT\r\n>AT5G57250.1_2245|0|training\r\nTGACAATTTATGCAAAGAAGGGTTGTTTCTTGATGCTGAGAAACTATTGGACAGTATGGTATCTAAGGGACTTGTGCCAAACATTATCATTTATAATTCGA\r\n>AT5G28919.1_580|0|training\r\nTCAGCAACTCTTTGGTCCTCAATGGATGAGAGCTCGGCCTCGACGTGGAAACTGTGGAGGCTTCAAATCACAAAAGAATCTTCTTCTGCAGACCGAGATTC\r\n>AT5G13660.2_1795|0|training\r\nAACCACATATACTTTGAAAATGGAAAGACCATTTATGGCGTTGTTCAAGAACTGAAGAATACACCTCAGGAGAAGTTGTTTGATGCTATTCAAAATGTTAC\r\n>AT5G61140.2_1254|0|training\r\nAGTCTGACAAAGCAGCTTCAAACACCCAATCTCGGATGCCTACCTATGGAACACAGGTTACTGTTCAAACAGAGTCTGCAAAGCAAATTGAAAAACTTCGG\r\n>AT5G61140.2_4173|0|training\r\nATAAGTTGTATGAATCGCTTTACAAATTTTCACATTTCAATCCAATACAGACTCAGATTTTTCATGTGTTATATCACACAGACAACAATGTTCTTGTAGGA\r\n>AT5G26749.2_477|0|training\r\nGTTAGTGGGAGACCAGGAACAGGTTGGTTTGATCTTCCGCCATCGCTAAAACCGCCTCCTGAGCAAGGCTATCCTCAGCTTCCCTTCATAGACTGGGGATA\r\n>AT1G09780.1_1772|1|testing\r\nGTGGAGTAGAAGAATTGAGAGCCTTATCAGTTTTTGAAGAGAGGGCTGAAACTCTCTAGTTATCTTTTGTTGCTTTTCTAATAATAAGAGTTTACACACAG\r\n>AT1G31812.1_443|1|testing\r\nTCCTCATCTGCAGTAACTTTATCTTAAGCATCAAAATAACATTGCATAAGACTTGTTCTTGCTCTTGTGTTTCTATCATATTTAAGCTATCTACTTTGTGA\r\n>AT1G77810.1_1523|1|testing\r\nGGCTTTGTTGTTTCTTCTACTTGAGTTAGATCATGTTAGTATAATCTTGGACAAAAGGGCAAATGAGCTAAAAAATGCATAACTAAAGAATTTTCAGACAA\r\n>AT1G14690.1_2242|1|testing\r\nATGAATGTAATCAAAAGGAGGAGTTACTGATACAGATCAAGTAACCGTAGACAATTAGTGGTCGTATGTGTGTGACTTTGAGTTGACTTGTGACGGATACT\r\n>AT1G60860.1_2599|1|testing\r\nGCTCATCGCATTGATGCTCCAATATTTACCTAATTCCCGAAGGAGATAGAACTCTAGGAAATGTCAAGATTCCGACCTACTGTATTAGCCTTTGTAATGTT\r\n>AT1G53320.1_1299|1|testing\r\nACTGGCTTTGCAAAAATGTAATGTTTTGATGTAATCATGTGTAAGTGTAAACACAAAGGTATGTGGAAAGGAGAAGCACATAAGTATTATTATGTAAGAAA\r\n>AT1G20840.1_2275|1|testing\r\nTTACATGAAAGTCCCGGAGACTAAAGGCATGCCTTTGGAAGTTATCACAGACTACTTTGCCTTTGGAGCTCAAGCTCAAGCTTCTGCTCCTTCTAAGGATA\r\n>AT1G56700.1_935|1|testing\r\nTAATGTTATCCCAAATGTGGCTATTCTTATTCATGAAATGTGCATCATGGACCGATTGTCTCCCCACGGGAAAAATTCGCTTATCAATAAATGGAATATAA\r\n>AT1G26580.1_2604|1|testing\r\nTGGGGTCCTCCTTCAAAAATGTTCCTATTAAAAAGTAGTGAGAGTTTTAGACTTAAAAGAATTTTCCAGCCTTTGTTTTTCATGTGGATTCTTGTGAATGG\r\n>AT1G36370.1_1866|1|testing\r\nCTTTGCAGTATGAGATGCCTGCTTCTCTTATTCGAATTGAATGAAAGAAAACTCCACACAACAGCTTTATTTACAGTTGAATTTTATCTTATCTCTGGGTC\r\n>AT1G51650.1_375|1|testing\r\nTACCAAGATTTGTTTTCTTTTTATTGTCAACAATGGAGCTTGAGTGAAAAACTCATTTCCGATCATAATAATGACACACTGAGTCTTGTGTATCTCTTTTC\r\n>AT1G30320.1_1665|1|testing\r\nGTGGTTGGTTCTCATGAGGCATTGGATTGAGTTTTTGGTCTTCTGAGTAAACCATGATTGGATTCTCAAAGCCCCTTTGTGTAATATAGAAATGGAATGCA\r\n>AT1G64430.1_1875|1|testing\r\nTAGCTCCCAACCTTAAGCACTCACACACTTGTCAACAAACCCGGTCAAAAACTCTGGAGCATCGCTAAAAGTTAAGTTTCTTTTGTCGGTCGCTATAAGTT\r\n>AT1G75380.1_1377|1|testing\r\nATGGAGATCGAAGAATGCTTCTGCACTTTACCCATTTCCCTAAAAAATAAACAAAAAAAAATGTATAATGTATGTATGTAGCGTGATGTGTACATATTACT\r\n>AT1G07920.1_1673|1|testing\r\nACACACACATTCTTCCTGTTTTTTGCTTTTTATTTGTTTTCTCATTTTGAACTGTTTTAAAATTTCTGTTATATGAATGAATGTTTTCCCTGCGGTTATTA\r\n>AT1G01090.1_1411|1|testing\r\nCAGATGTGAGGACCCCAAGTTTACCGAAGGCACAGCTCAAGTCTGAGAAGACAAGTTTAACCATAAGCTGTCTACTGTCTCTTCGATGTTTCTATATATCT\r\n>AT1G22660.1_1901|1|testing\r\nTTGTGCTGTGTAGTCTTATAAAAATCCACTAACATTGTAGATTAATTTAAACTCAGTTTTGACAAATTTTATCGATTCTAGGCTCATTCCCTGGCAAGTTT\r\n>AT1G15180.1_1527|1|testing\r\nAAAGCGAGAAATCGAATGGCTTTGGCCTATGGAACGTAAGGCGCTGCAGAACAGCTAAAGATCATAGTGAGCATAGGTTCCTCCGGTTTTACCAGTTTTGT\r\n>AT1G48490.1_4123|1|testing\r\nGTGTTTTGCGGTTTGATATTTGTTTGGATTTGTGGTTCAGCATATATGGGACATGGTCTCTTAGGCTTTTGCGTTCCACCTTCATAGAAGGGTTGTGAAAT\r\n>AT1G53530.1_802|1|testing\r\nCTTTTTGGCAGTAATAGAAGAAAAGCCATGGTCCTGATATTGTTTCTGAAACCCGAACTTCAATATCAAATGTTAAGATTCATATTGTTGGTATCGAAAAA\r\n>AT1G62880.1_765|1|testing\r\nGGCTTTTAGGTTATGTAAGTTAATTAATGTGGCATTAGAGAGCTGTGTAAACCAGATTTTATAGTCATTAGAATTTCATTGTGGATCTTTGTGGTGAAGCC\r\n>AT1G06290.1_2176|1|testing\r\nAATTCCCATATATCTCTTATAAAAGTTATGTTTCCACAATATCTACAGAAACTGTTGTAAGCTCGTCATAATAAAAGGGTATATATGATATGTATCCAGGG\r\n>AT1G74560.3_983|1|testing\r\nCAGATGTGTAAAGTTTGTGTTATGAGGTTCTCAATTTTAGCAATGATGAGACTAAGCTTTCTCTTTTGGAATATTTAGTTTATTTACTATCAATAGCTACA\r\n>AT1G70620.3_177|1|testing\r\nCCACCGCCTCCGACGGATCCTTACCACCAATACTATCAGCATCAGGCGAGACCACCGGTGCCTCCTCCTACGCAGCCCGGTGGTCCTCCTGCATGGTACTC\r\n>AT1G11330.2_2875|1|testing\r\nTCTCAGTCTGTTTATATACATAATAGTATGTAATATACACGTTTTGAGAAACTCCTATGTTTACAAATTTTGTTATCTGCGTCTGTGCAATGGTTAGATTA\r\n>AT1G49720.2_1375|1|testing\r\nTCAAAGCAAGAAGAACCTGCTAATGTAATACAGGACCACTCAAAAGGAAGACACTGGGAGAGTAATATGTAATAGAAGATAGTGCTACTGTACAGGAGAAA\r\n>AT2G42600.2_2977|1|testing\r\nTGAAGATACGGTTATCCTCACCATGAAGGGTATCGCTGCTGGTATGCAAAACACCGGTTAAGGCAGTTTAAAACGTTCTTGTACCATTCCCTAAATCTACG\r\n>AT2G43750.1_1440|1|testing\r\nAATGCAGCCCGAGCTTTGATTTTCTTCTGTAATTTCGTGACCAACAAGGAACCTCTTCTTTGATTTATTGCTGATTGTTTTTCTTCTAATAGACGTTTCTG\r\n>AT2G15695.1_1401|1|testing\r\nAAGACTATGAATGAAATCGCAGAAACTGAGCAAGGTACTGGGTGATGTGAACCATATGGGGAAGTAGTAGAGAGATGTTTAGAAAGGAAGAGGATGTATAG\r\n>AT2G44100.1_1567|1|testing\r\nCTCTTCTTAAAAGTTGTCTCACCAAATGTTCTGTTAAAATACTAAATCAAACCGATCTCATCATGCGTACCTATTCCCGGTTATCGCAGTCTGTTTTTTTC\r\n>AT2G26780.1_5525|1|testing\r\nGTCGTTGTTGAGAAAATCCAGGGATGCTCTTGCAAATCTCCCTTCGTTAAACTAAGCAAGCACAGAGAAGATTTTAGTTTTATGCCTGAAGTTGATATAAA\r\n>AT2G33470.1_967|1|testing\r\nTCTTTGCCGGAATCTTTGTCTGTTTTAACTTTTCTCCTTCCAATTATAGAACCTCCAAAAAGAAACAGAATAATGTGTTGGTTTCTATCTGAATGTTCACT\r\n>AT2G21160.1_1026|1|testing\r\nATTTAGGGTTTTAAACGACACTTTTTTTGTTCCAGCATTGTACTCTTTAGACAATCTTTACTTCTTGTCATAAATATTCTCCTCATGAAACAAGTTAACTT\r\n>AT2G42680.1_596|1|testing\r\nAATGCCGTAACTTTGCCAAGAAGAATATTTTCTGATTGTAAGAAAGCAAAACCGTTTGAATGTTTGTTTCGTTGATGGAATCTCTATCTCATAAACTCATA\r\n>AT2G43090.1_879|1|testing\r\nAGGATCTTGATCCAATAATAAGAATATGTAATGTTTCCAAAAGCTTATGAACCTAATCTATGTTTTATGAATATATATGACTATCGGCTTTAGTCTTCAGT\r\n>AT2G40765.1_439|1|testing\r\nTCATTTCTTCAATGTAGTTGACTGATTTGTCTTCTCAAATGTTATAACAAACAAGAAAAGCACTTACTCCAAGTTACTTGAAAAGAGAACCCATTTTGCAT\r\n>AT2G28450.1_2576|1|testing\r\nTGACCACTGCGAAATGGTAATGCTCCTTGAGAGGTAAGAATACGAAATAAACTCTTTAAGAGAATGATGTAGCACCAAAAGAACAAGCAACAACTATTTTT\r\n>AT2G42910.1_1180|1|testing\r\nCTGCAGATTTGAAGCAGTAGAGATAAAGCCTGGTTCTTTGCTCGTTTTGGACTTTTGGTGGTTTTATACTCTTAAGAGATGTGCTTTGGATGATCATTTAT\r\n>AT2G24390.1_701|1|testing\r\nGATTTGGGGTTTTGTGGTATTACTTAATTCAACTGATAAGGAATAAGAAAACAGCTACAGATTCTTGTGCGGTATGTTATTATACAATACACATATAGACA\r\n>AT2G01250.1_858|1|testing\r\nAATGAGCTTATCAGGAGGATGAATTAGAATGTTATCGTTTTCAATGTCAAACTTCTCTGCGTTTTCATTATGTGCCTCCTCCTGGATTTTGATCTTCTTTC\r\n>AT2G01170.1_1639|1|testing\r\nCAGTGCCCGCCACTGGTTTACGGGTCCCATCTCCAACATTCTTAGCTGAAACAACGTTTCAGGGGTTGATTTATAGTAAAGCCATTGTTAGCTAGCTGATA\r\n>AT2G05630.2_700|1|testing\r\nTATTTCTCTGCTTGTCTCTAGTTTTCATGACATTGGACGAAGCTTTTGAAACTTGCATGCTATGTTATTAACATGATAAGGTCTTCCGTTCATGGTGTTAA\r\n>AT3G01850.1_876|1|testing\r\nATGTTTTAAAATCATCTCGTGAATCGTGATACTTAGTCTTGGTTCCAAGAACTGTATAACGTCATTTTGAGTTATTAATTCCCTCACCACACAGATTATTT\r\n>AT3G49600.1_3574|1|testing\r\nGTTTTTTTGTAAAGGCAGGCAAGGCTTTGGAGCTTTATTTTGTGTAAAAAACAAACGCAAAGATTTGGAGAAAGCTTAGCACAAGCTGAATTTGTGTAGAT\r\n>AT3G55020.1_2770|1|testing\r\nAGTTCTCTCAGTCACCCTTTTTTCATAATTCCGGATTGAATTTTGGGAGAACTTTTAAATACATTCATTTGTTTGTTTGTGGTATGCTGCTATAAATATAT\r\n>AT3G08620.1_1145|1|testing\r\nGCTTACCCTCTGATCCACACACTGATGCTTATACACAAAGCACCAAGAGAACAGTTTCCTCCTTGACCGGGGTTTGATGCATTGTAACCATCAAAGATATT\r\n>AT3G50370.1_6985|1|testing\r\nGATAATTAGATTTTGTTCTCTTTACTCGTTTGGGGATTCATTATATGGGGACTTTGGTAATGCTTAATTTCGTCATGGTTGGTAAAAATATTGTCGTGAGG\r\n>AT3G62900.1_4798|1|testing\r\nGCAGTCTTCCGGCAAAGTTCTTAATTAGGCTTTGGTTCGTGTAAGCTAAAACAATATGTTATGTTTTTGACTGGAAATTCTCGACTGAGTCTATATGTATA\r\n>AT3G11510.1_644|1|testing\r\nTCGAAGTTAGTTTTGTCTCTCTCCAATTTATCTTTCCAGTTGCTTTGAGAACATTATAAGCTGTGTTTTTTTGTATTTGGAGTTTTTGGTATTGAGAAAAA\r\n>AT3G07560.1_1199|1|testing\r\nTAGAAGATAAACCGTGTAGCAGCCTGCAACACAGATTGGGATGTACGAAAACCAGATGTTTGTTTGCAAATTGAGTCTCTTCTTCTCTTCTCTCTATCTCT\r\n>AT1G67210.1_567|0|testing\r\nAAAATTCCTTGTCCGAGGATCAAGAACAAGTACTAGAAGCTGGTGATGAGACATACTTTCCTGCTTTGCGTGTGGGATTGCAGAAGACATCATCTGTATCA\r\n>AT1G27910.1_2490|0|testing\r\nCTGACACTATTCAGGGAACTGAGGCAAAGGGATCAAACCCATCTCACAGAACCGCAGCATACAGAAGTCACAAGCCCCGAGGACGGATTCTCTGTTGCTTC\r\n>AT1G01980.1_504|0|testing\r\nCCGGCGCTACTCTCGGCGAAGTTTATTACAACATTTGGCAGAGCAGCAAAACTCACGGCACTCACGGATTTCCCGCCGGTGTTTGTCCCACAGTAGGCGCT\r\n>AT1G18590.1_635|0|testing\r\nACGTTTGTGTCGATGTGGACTTTTGCTCACAAGGAGAGATCACAACAAGGACCAGTGGTTAGCATTGAGGAAGCTTTTGATAAGTACTGTCAAGGTTTATC\r\n>AT1G31710.1_1548|0|testing\r\nTGACCACGAGGTCTCCAAAATCTGTTAACACACCGAGAAAAACCTATTGGACAACGAAGCCAAAGACGGCCAAGACCGAGGCAGAGGCTCGGGTGAAACTA\r\n>AT1G52550.1_183|0|testing\r\nCGGTCGTCTCCACTTCCTTCTCAGACCCTTTTCCTCGTCCCCACTCCAAAACCTGTACGACGCATCGCGGTCGCTCCTCTCGGCCCTCCAACGCCGCCTAG\r\n>AT1G76965.1_359|0|testing\r\nCCCGAGGAACCTGTGAAGGTGGTGCCAACGCCAATGCCACAAGTTTGCGAACCGAAAGTTAGACATTGCATCAATGTACATGTATACGGACGCGCCGGGCA\r\n>AT1G62870.1_2577|0|testing\r\nCATCCTCAGTGTGACTTGTTAATTTTTACCAAATTTAGTTTTTCACTAGAACTTGGCCATTTTGTAGGATTGCTTGAATTCATTTTTTTTGTTGTTAACTT\r\n>AT1G48360.2_1322|0|testing\r\nGTTACAATGATGGAACGAGAATAAATCTAGCAACAGTAATTCTAGAAAGAACAGGACTATGTGCTAAGGTATCAAGTACAGCAGAATCTCTCATATGGCGC\r\n>AT2G23700.1_1710|0|testing\r\nGTTTTCACCACAAGACCAGTATGATATGTGGAGTCCAAGCTTCAGAAAAAACTCGTCTTTCGATGACCAGTTTGAATTCAGCGGACCTTATAGCTCAATGA\r\n>AT2G19900.1_1217|0|testing\r\nAAGGGATTGATTGTTAACTCCCGCAAAGATTCACTTCAAGACTTTAAGAAACCATGGGCTCATGAACATGAACCAGTCAAAGACCTCTTAGGTGCTATCAA\r\n>AT2G31160.1_306|0|testing\r\nCGAGAACCAGAAGAGGAGAGACTGGAACACGTTCGGACAGTACTTAAGGAACCATCGGCCACCGCTTTCGCTTTCCCGATGCAGTGGAGCTCACGTGCTCG\r\n>AT2G46650.1_196|0|testing\r\nACCAAAAGTAATCATATGGCGAATCTAATTTCGTTTCACGATGTGGCTAAACATAAGTGCAAGAACGATTGTTGGATTCTCATCCATGGAAAGGTCTATGA\r\n>AT3G20475.1_1187|0|testing\r\nTGGTCATTGGAGTCATTGATGTTACTAGAAGCAAAGAGAGGGGATATCAAACTTTGGTTAAAGAAGGATTCTGTGCTGAGTTGGATGAGCTCAGGCAAATA\r\n>AT3G10020.1_194|0|testing\r\nAGCACAAGAATGAAGAAGGCCGGAAATCTGTTGATAAGTTCGAAGTGAAGACACGTAATCCGGAGACGATCAAGAGCGTTGAGCGGAAGCTTATGGAGAAA\r\n>AT3G14890.1_395|0|testing\r\nTTATCCGCTTTAGAGAAAGAAGATCAAGATGCTTTGACGAAATTGGTGGAACAATGTGGTAAAGTACCTGCAAAAAAACCTGATGAGAAGAAGGGGAAGGC\r\n>AT3G14890.1_848|0|testing\r\nGATGAAGCTATAGCTGATAATGAGCTAACGGAGGAGACCAAAAAAGGAAAACATTCTCCTGTTGCAAAATTGGTGGAACAACCTGGCGAGCCTGCAAAAGA\r\n>AT3G11964.1_2690|0|testing\r\nCCCGGTTCTGTTGTCAATGCAGTTGTTCTTGATATATCTAGGGCAGAGAGACTAGTTGATTTGTCTTTGAGGCCTGAGCTCTTGAACAACTTAACCAAAGA\r\n>AT3G48470.1_1372|0|testing\r\nCGTAACAGATATATCAGATATAACTGCAGCTCTTGGGCTTTGCCTGGAGAACATGTCAAGAGAAGAACTAGATAGAACAAAGGATGTAATGCACAGTATTC\r\n>AT3G53480.1_3442|0|testing\r\nAATCCAGCAACATGGATGCTTGATGTTAGTTCACAGTCGGTAGAAATTGAACTTGGTGTCGATTTCGCAAAAATCTACCATGACTCTGCTCTTTACAAGCG\r\n>AT3G59100.1_4895|0|testing\r\nAAGTTTGCGGAGAACTACAGGTTGTATTCGAGAAGTCACTTTGTGAAGGGACTAGAGCTGCTTTTATTGCTAGTTGTTTATCAAATCTATGGGCATTCATA\r\n>AT3G44050.1_2522|0|testing\r\nCAGAACAGTGCTGAAATTGCTTTAGAGGTTGAAAAAAGTGCAGCTGAAGAACAGAAGAAAATGATAGGAAACCTGGAGAATCAGCTAACCGAGATGCACGA\r\n>AT3G18830.1_1030|0|testing\r\nAAGCTTCCGGTATCGACGCGGTGGTTCTCTTCTCACCGCGAATTTTCAAAACCGCCGGACTCAAAACCGATCACCAACAGCTTCTAGCGACTGTAGCAGTA\r\n>AT3G06433.1_3075|0|testing\r\nAGTCGTTATTCGCATACCCAACCTACGCGAAGAAATTCAGGTTGTCTTAAACCAACCCAGCTCGGCAATTCCTCAGACCGCTATAAACGAGATACCAAGTG\r\n>AT3G23590.1_3716|0|testing\r\nACGATCCCATCTTGGTTTCTATCAACTGACAAATCAGACCGAGAACAAGGACCATCGGATCTAGTTGCAGAGCTAAGAGGTCATGCCCTTGCCTACTTTGT\r\n>AT3G42670.1_533|0|testing\r\nTACTATAGATGGAGATACTCTGAGGACTGTTCTTCGTTGGTGAAAACAAGACTAAACTTAGGGAAGTTCTTGCCTGATCTTACATGGTTGCTTGTTACATC\r\n>AT3G42670.1_2996|0|testing\r\nTACACATTGTTGATGAATTCCACTGATGTACAGCACAAGAGTCTTACCAAACTTCAGAACATAATGTCAACTTACCATGGATATCCACTCGAGCTCGAGTT\r\n>AT3G25560.3_294|0|testing\r\nCTCTGCACCTTAGAGATTAATACTCTCAAGAAAAACAAGTTTTGATTCGGACAAAGATGTTGCAAGGAAGAAGAGAAGCAAAAAAGAGTTATGCTTTGTTC\r\n>AT4G35380.1_1032|0|testing\r\nCTTTGGAGTTGCTTAAAGTCATTATTGACAATGGTGGTTCTGTTTGGCGGACTAATGAAAGCTTCATCAATGCCGTTAAGCAATACTTATGCTTATCACTA\r\n>AT4G36080.1_7292|0|testing\r\nGAATCTGCTGATGTTGGGGCAGTCGTATCTAATATAAAGTTGGTCTTGGAACTTATTGATGAAAGGGTTATGCTTTTAGCGGATTGCAAAAGACCTGTGAC\r\n>AT4G36840.1_1483|0|testing\r\nGGGGAAGATTGAGTGGTCCAATGTTGTCTTCAAACTTGATCCTCTCTCAAACTCATATAGCGTTGATGTCTTATTTTCTGCTTCTGTCCATTTGTGATATA\r\n>AT4G01400.1_1569|0|testing\r\nCCCGCATTGACGCGATTGTTGAGCGAGGGAATTGCATCGAAGGCGTGAAGACTGCTTTGGAATCCGAGGATTACGAATCTGCTGCGAAATTTGTACAGAGA\r\n>AT4G27750.1_266|0|testing\r\nTCTCCTTCCTTCGCATCCGTGGTCTTAGATCTCTTCTCAAAACTCTCCGAACTGTCGCTGATTCAGATTCAATCATTCGTCTCTTCTCTCATACCCAAACC\r\n>AT4G16020.2_392|0|testing\r\nAAGCTTCTTCTTCAGGGAAGTAATCGAGATGGACTCTATGTGCTGGATGAACCAAAGCTTCTGGTGTTCTACTCTTCTCGCCAAGTTGCAGCGTCTGATGA\r\n>AT4G11110.1_1447|0|testing\r\nAGAGTCTTTTGACAGCAACATGAACAAAGAGACTTTAAGTCAACTCGAAAACCCTCTGGTTAGAAGACGGTTAGGAGATACTTCTAGTCTCTCTATCCCTG\r\n>AT4G38150.1_349|0|testing\r\nCTCGAACAGTTCAAGCTTGGAGTCAATCAGGATTCACGGGAAACCCCCAAACCGGAACAATACCCGCAGGAGCCCTTACCGCCGCCTGAGGATTCCGATGA\r\n>AT4G23050.2_1223|0|testing\r\nTGGAGCTGAGGGTTTGATACATAATGGAGATCGCTTTCAGTATATTGGGAACCTGGGACAAAGTAAACCTCCCAGAGGACTAGAGAGTGGTTTGGTGTCTG\r\n>AT4G12020.2_695|0|testing\r\nAAAAAATGCAGCCATGAAGATTGCACAGGATTTGCTAGGGGAAGATCAGGACTCTGTCTCATGCACGGTGGGGGAAAGAGATGCCAAAGAGAGAACTGCAC\r\n>AT4G12020.2_5114|0|testing\r\nCGATATCGTGGCACAACTAAGGACGAGTCGAATTTGTACATTTTTCTTGAACTTGTAACCCAAGGGTCCCTTCGAAAACTCTACCAAAGAAACCAGCTTGG\r\n>AT4G02760.3_761|0|testing\r\nGATGTTGATAATGGAGTTGTGTGCGTAATGATCCATCGGGCTGGAAAAGAACTCAGATCCCTCAAACTTGGTTCTATTTCTTCCTCAGCTGAACCTACTAC\r\n>AT5G65720.1_1486|0|testing\r\nCATTCAATGGTCTCAACACTGATTCAACAGTTCCACTCAAACTGTGCGGGACAAGAGGGAATCTCCAGTCTGTGGTCAGCCGGGGTATATGAGAGCCATAC\r\n>AT5G19600.1_1285|0|testing\r\nCAACGGGGCCATTTTCAAAGACAGCAGTGAACTACAACGCGGGGACAAAGACACCGATGTCGAATGTAGTAATGGGCGTTTGCATGATGCTTGTGCTTCTC\r\n>AT5G02490.1_1454|0|testing\r\nGCCTGGAGTGTTGATCCAAGTTTTTGAAGGTGAGAGGGCTAGGACCAAGGACAACAACCTCCTCGGTAAATTTGAGCTTTCTGGAATTCCCCCTGCTCCAC\r\n>AT5G22920.1_138|0|testing\r\nAACAAATTTTGATATCTGATTGGTGTTGATTCCAAGTAAGAAAGATCAAAACTTTAGGTAAAGTATGGATATGGGTTTCCATGAAAATGAGCAAAATCAAG\r\n>AT5G12960.1_581|0|testing\r\nAAAGAAGCTGGTCTTAATGCTCCTGGAGTTCCCTATGGAGGATGGGAGAAACCAGATAGTGAACTCCGTGGCCATTTTGTCGGTCACTATTTGAGTGCAAC\r\n>AT5G11230.1_249|0|testing\r\nTCATCATCAAGGTTTTCAAATTCGTCGAGCCAGTTAAAATGACTCGCGAGACTTACCTGAGATCCGTCGTACCGATCGGTGCTTTGTACGCTCTCTCACTC\r\n>AT5G32481.1_4454|0|testing\r\nAATGATAGAGCGATCTCAGGAGAAGGATATGAGACTGAAAGAGTGAAAGAACTTAAAAAGAGGTCTAATAAGCAAGATGAAACTATAGAGAAGCTAGCCCA";
  const example = () => {
    //readFile(file)
    setDAN_text(text);
  };
  const [selectMulMethodData_1, setSelectMulMethodData_1] = useState([]);
  const [selectMulMethodData_2, setSelectMulMethodData_2] = useState([]);
  const [selectMulMethodData_3, setSelectMulMethodData_3] = useState([]);

  const selectMulMethod_1 = (value) => {
    setSelectMulMethodData_1(value);
    console.log(`selected ${value}`);
  };
  const selectMulMethod_2 = (value) => {
    setSelectMulMethodData_2(value);

    console.log(`selected ${value}`);
  };
  const selectMulMethod_3 = (value) => {
    setSelectMulMethodData_2(value);

    console.log(`selected ${value}`);
  };

  const daraCollection = [
    <div className="serverForm-descriptions-con-outer">
      <div className="serverForm-form-text-con">
        <div>
          Enter the query DNA sequences in special FASTA format:(maximum2000
          sequences for each submission)
          <a
            onClick={() => {
              example();
            }}
          >
            example
          </a>
        </div>
      </div>
      <div className="descriptions-con-Dragger">
        <TextArea
          value={DAN_text}
          onChange={({ target: { value } }) => {
            setDAN_text(value);
          }}
          autoSize={{ minRows: 4, maxRows: 4 }}
        />
      </div>
    </div>,

    <div className="descriptions-con-Dragger">
      <div className="serverForm-form-text-con">Or upload a file</div>
      <Dragger {...props} className="testAdd-Dragger-con">
        <p className="ant-upload-drag-icon">
          <InboxOutlined />
        </p>
        <p className="ant-upload-text">
          <div className="serverForm-form-text-con">
            Click or drag file to this area to upload
          </div>
        </p>
      </Dragger>
    </div>,
    <div className="descriptions-con-Dragger">
      <div className="descriptions-con-Dragger">
        {testAddValue == 1 ? (
          <Dragger {...testProps} className="testAdd-Dragger-con">
            <p className="ant-upload-drag-icon">
              <InboxOutlined />
            </p>
            <p className="ant-upload-text">
              <div className="serverForm-form-text-con">
                Click or drag file to this area to upload
              </div>
            </p>

            {/* <Button icon={<UploadOutlined />}>Select File</Button> */}
          </Dragger>
        ) : (
          ""
        )}
      </div>
      <div className="testAdd-Dragger-con-button">
        <Button
          className="button-serverForm-button-timeline"
          onClick={() => {
            setTestAddValue(1);
          }}
        >
          Add test set
        </Button>
        <Button
          className="button-serverForm-button-timeline"
          onClick={() => {
            setTestAddValue(0);
          }}
        >
          Remove test set
        </Button>
      </div>
    </div>,
  ];
  const selectMethod = [
    <Card
      title={<div className="card-title-text">Deep Learning:</div>}
      className="card-selectMethod"
    >
      <Select
        mode="multiple"
        style={{ width: "100%" }}
        placeholder="select methord"
        defaultValue={[]}
        onChange={selectMulMethod_1}
        optionLabelProp="label"
      >
        <Option value="CNN" label="CNN">
          <div className="demo-option-label-item">CNN</div>
        </Option>
        <Option value="DNN" label="DNN">
          <div className="demo-option-label-item">DNN</div>
        </Option>
      </Select>
    </Card>,
    <Card
      title={<div className="card-title-text">GCN:</div>}
      className="card-selectMethod"
    >
      <Select
        mode="multiple"
        style={{ width: "100%" }}
        placeholder="select methord"
        defaultValue={[]}
        onChange={selectMulMethod_2}
        optionLabelProp="label"
      >
        <Option value="TestGCN" label="TestGCN">
          <div className="demo-option-label-item">TestGCN</div>
        </Option>
      </Select>
    </Card>,
    <Card
      title={<div className="card-title-text">Visulation:</div>}
      className="card-selectMethod"
    >
      <Select
        mode="multiple"
        style={{ width: "100%" }}
        placeholder="select methord"
        defaultValue={[]}
        onChange={selectMulMethod_3}
        optionLabelProp="label"
      >
        <Option value="Bert" label="Bert">
          <div className="demo-option-label-item">Bert</div>
        </Option>
        <Option value="self-attention" label="self-attention">
          <div className="demo-option-label-item">Self-attention</div>
        </Option>
        <Option value="Transformer" label="Transformer">
          <div className="demo-option-label-item">Transformer</div>
        </Option>
      </Select>
    </Card>,
  ];
  const customDot = (dot, { status, index }) => (
    <Popover
      content={
        <span>
          step {index} status: {status}
        </span>
      }
    >
      {dot}
    </Popover>
  );
  const [stepStatus_step_1, setStepStatus_step_1] = useState("gray");
  const [stepStatus_step_2, setStepStatus_step_2] = useState("gray");
  const [stepStatus_step_3, setStepStatus_step_3] = useState("gray");
  const [stepStatus_step_4, setStepStatus_step_4] = useState("gray");
  const [stepStatus_step_5, setStepStatus_step_5] = useState("gray");
  useEffect(() => {
    if (fileList.length > 0 || DAN_text) {
      setStepStatus_step_1("blue")
      // setStepStatus({
      //   step_1: "blue",
      //   step_2: stepStatus.step_2,
      //   step_3: stepStatus.step_3,
      //   step_4: stepStatus.step_4,
      //   step_5: stepStatus.step_5,
      // });

      console.log(DAN_text.length);
    } else {
      setStepStatus_step_1("gray")

      // setStepStatus({
      //   step_1: "gray",
      //   step_2: stepStatus.step_2,
      //   step_3: stepStatus.step_3,
      //   step_4: stepStatus.step_4,
      //   step_5: stepStatus.step_5,
      // });
      console.log(DAN_text,"123");
    }
    if (
      selectMulMethodData_1.length > 0 ||
      selectMulMethodData_2.length > 0 ||
      selectMulMethodData_3.length > 0
    ) {
      setStepStatus_step_3("blue")
      // setStepStatus({
      //   step_1: stepStatus.step_1,
      //   step_2: "blue",
      //   step_3: "blue",
      //   step_4: stepStatus.step_4,
      //   step_5: stepStatus.step_5,
      // });
      console.log(selectMulMethodData_1.length,selectMulMethodData_2.length,selectMulMethodData_3.length)
    } else {
      // setStepStatus({
      //   step_1: stepStatus.step_1,
      //   step_2: "blue",
      //   step_3: "gray",
      //   step_4: stepStatus.step_4,
      //   step_5: stepStatus.step_5,
      // });
      setStepStatus_step_3("gray")
      console.log("asdasds")
    }
    if (eMail != "") {
      // setStepStatus({
      //   step_1: stepStatus.step_1,
      //   step_2: stepStatus.step_2,
      //   step_3: stepStatus.step_3,
      //   step_4: "gray",
      //   step_5: stepStatus.step_5,
      // });
      setStepStatus_step_4("blue")
    }else{
      setStepStatus_step_4("gray")

    }

    if((fileList.length > 0 || DAN_text)&&(selectMulMethodData_1.length+selectMulMethodData_2.length+selectMulMethodData_3.length)>0&&eMail != ""){
      setStepStatus_step_5("blue")
    }else{
      setStepStatus_step_5("gray")
    }
  }, [
    fileList,
    DAN_text,
    selectMulMethodData_1,
    selectMulMethodData_2,
    selectMulMethodData_3,
    eMail,
    current,
  ]);
  return (
    <div className="serverForm-body-outer">
      <div className="serverForm-body-con">
        <Modal
          title="Success"
          visible={isModalVisible}
          onOk={handleOk}
          closable={false}
          mask
          onCancel={handleOk}
        >
          <Result
            title="Successfully push your data to our server!"
            subTitle={
              "Your request time is " +
              resultData.requestTime +
              ", your jobID is " +
              resultData.jobId +
              " please wait."
            }
          />
        </Modal>
        <div className="serverForm-timeline-serverForm-body">
          <div>
            <Timeline>
              <Timeline.Item color={stepStatus_step_1}>
                {" "}
                <List
                  header={
                    <div className="Data-load">
                      <strong>Data load</strong>
                    </div>
                  }
                  footer={<div></div>}
                  bordered
                  dataSource={daraCollection}
                  renderItem={(item) => <List.Item>{item}</List.Item>}
                />
              </Timeline.Item>
              <Timeline.Item color={stepStatus_step_2}>
                <div className="serverform-Collapse">
                  <Collapse onChange={() => {
                    setStepStatus_step_2("blue")
                  }}>
                    <Panel
                      header={
                        <div className="serverform-Collapse-ADVANCED">
                          <strong>Advance Options</strong>
                        </div>
                      }
                      key="1"
                    >
                      <p>
                        <Radio.Group
                          onChange={(e) => {
                            setAValue(e.target.value);
                          }}
                          value={aValue}
                        >
                          <Radio value={1}>balanced data</Radio>
                          <Radio value={2}>imbalanced data</Radio>
                        </Radio.Group>
                      </p>
                      <p>
                        <Radio.Group
                          onChange={(e) => {
                            setBValue(e.target.value);
                          }}
                          value={bValue}
                        >
                          <Radio value={1}>CD-Hit</Radio>
                          <Radio value={2}>none CD-Hit</Radio>
                        </Radio.Group>
                      </p>
                    </Panel>
                  </Collapse>
                </div>
              </Timeline.Item>
              <Timeline.Item color={stepStatus_step_3}>
                {" "}
                <List
                  grid={{ gutter: 16, column: 3 }}
                  header={<div className="Data-load">Select Method</div>}
                  bordered
                  dataSource={selectMethod}
                  renderItem={(item) => <List.Item>{item}</List.Item>}
                />
              </Timeline.Item>
              <Timeline.Item color={stepStatus_step_4}>
                <List
                  header={
                    <div className="Data-load">
                      <strong>EMail</strong>
                    </div>
                  }
                  bordered
                  dataSource={[
                    <div className="descriptions-con">
                      <Input
                        value={eMail}
                        onChange={({ target: { value } }) => {
                          setEMail(value);
                        }}
                      />
                      <div className="serverForm-form-text-con">
                        Optional: The running time usually takes a few hours,
                        and can be more than 10 hours if there are more than
                        5000 cells in your data. Hence, we strongly recommend
                        you to leave your email below, and you will be notified
                        by email when the job is done:
                      </div>
                    </div>,
                  ]}
                  renderItem={(item) => <List.Item>{item}</List.Item>}
                />
              </Timeline.Item>
              <Timeline.Item color={stepStatus_step_5}>
                <List
                  header={
                    <div className="Data-load">
                      <strong>Submit</strong>
                    </div>
                  }
                  bordered
                  dataSource={[
                    <div className="button-serverForm-timeline-outer">
                      <Button
                        className="button-serverForm-button-timeline"
                        onClick={() => submit()}
                        disabled={uploading}
                      >
                        {uploading ? <Spin indicator={antIcon} /> : ""} submit
                      </Button>{" "}
                      <Button
                        className="button-serverForm-button-timeline"
                        onClick={() => {
                          resetData();
                        }}
                      >
                        reset
                      </Button>
                      <Button
                        className="button-serverForm-button-timeline"
                        onClick={() => {
                          store.store.servers.changeHomeStatue(2);
                        }}
                      >
                        return
                      </Button>
                    </div>,
                  ]}
                  renderItem={(item) => <List.Item>{item}</List.Item>}
                />
              </Timeline.Item>
            </Timeline>
          </div>
        </div>
      </div>
    </div>
  );
}

export default inject("store")(observer(ServerForm));
